### ISSUE TITLE
Provide samples in Components and Validators documentation in FileVault DocView format

### ISSUE THREAD

**Issue by kwin** [wcm-io/io.wcm.wcm.ui.granite#11]
Currently both https://wcm.io/wcm/ui/granite/components.html and https://wcm.io/wcm/ui/granite/validation.html use JSON serialisation format (primarily used in Sling context). I think [FileVault DocView format](https://jackrabbit.apache.org/filevault/docview.html) is more common in the AEM ecosystem.

**Comment by stefanseifert** [comment]
it's currently common practice thorough the whole wcm.io documentation to use the JSON notation. but you're right that switching to filevault would be more user-friendly (or provide something like view the content structure in one or the other way).

i will take a note, but i will probably take a while to change this.

**Comment by stefanseifert** [comment]
i've updated the documentation to provide code snippets for both FileVault and JSON view (the former is derived automatically from the lattern).
https://github.com/wcm-io/io.wcm.wcm.ui.granite/pull/14
https://github.com/wcm-io/io.wcm.maven.skins.reflow-maven-skin/pull/2

**Comment by kwin** [comment]
@stefanseifert Thanks, looks great.
